[package]
name = "koradar-tracer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
qemu-plugin-sys = "10.1.0-v2" # Using a recent version compatible with modern QEMU
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

